<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 11/11/16
 * Time: 3:54 PM
 */
class FlowPanel extends DataObject
{
    private static $db = array(
        'PanelTitle' => 'Text',
        'PanelText' => 'HTMLText',
        'PanelUrlLink' => 'Varchar(100)',
        'HashColor' => "Varchar(20)",
        'PanelType' => "Enum('Full, Half, Third, Quarter', 'Third')",
    );

    /**
     * Summary Fields For A Panel
     */
    private static $summary_fields = array(
        'GridThumbnail' => '',
        'PanelTitle' => 'Title of Panel',
        'PanelType' => 'width of panel',
        'PanelUrlLink' => 'URL of page panel will link to'
    );

    public function getGridThumbnail()
    {
        if ($this->PanelImage()->exists()) {
            return $this->PanelImage()->SetWidth(100);
        }

        return '(no image)';
    }

    private static $has_one = array(
        'PanelImage' => 'Image',
        'FlowLandingPage' => 'FlowLandingPage'
    );

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        return $fields; // TODO: Change the autogenerated stub
    }
}
